---
driver:
  name: vagrant
  synced_folders:
  - ["./", "/cookbook"]

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31

platforms:
  - name: bento/centos-6.7

suites:
  - name: ipt1
    driver:
      vm_hostname: ipt1.test.manasg.com
      customize:
        memory: 2048
        cpus: 2
    run_list:
      - 'mg_golang'
